# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('homeTeam', models.CharField(max_length=200)),
                ('awayTeam', models.CharField(max_length=200)),
                ('prettyDate', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('league', 'homeTeam', 'awayTeam', 'date')]),
        ),
    ]
